### ISSUE TITLE
可以支持Null safety吗

### ISSUE THREAD

**Issue by lan2000** [CodeGather/alarm_calendar#3]
你好，可以支持Null safety吗

**Comment by lan2000** [comment]
荣耀v10 ，android 10，设置提醒时间，打开日历里面看事件，并没有开启提醒功能

**Comment by CodeGather** [comment]
最近有点忙，不好意思

**Comment by lan2000** [comment]
有空再更新吧。对了我这边android10 荣耀v10，测试发现：&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
valueReminder.put(CalendarContract.Reminders.METHOD, CalendarContract.Reminders.METHOD_ALARM);//设置日历提醒，比如提前10分钟，设置不起作用
valueReminder.put(CalendarContract.Reminders.METHOD, CalendarContract.Reminders.METHOD_ALERT);//换成这句之后，设置提醒就行






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月13日(星期二) 下午4:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CodeGather/alarm_calendar] 可以支持Null safety吗 (#3)





 
最近有点忙，不好意思
