### ISSUE TITLE
ios 上删除日程返回结果成功,实际并未删除

### ISSUE THREAD

**Issue by wholwh** [CodeGather/alarm_calendar#5]
ios 上删除日程返回结果成功,实际并未删除

ios 14.5

**Comment by CodeGather** [comment]
已处理

**Comment by wholwh** [comment]
更新到 0.0.5
删除日程报错
1.添加的日程id和删除的日程id是一致的,日历里查看也是有的
2.权限给了日历和提醒权限
![image](https://user-images.githubusercontent.com/7368853/128162471-21cdc208-5516-4d01-9af1-0c4bec4984dc.png)

**Comment by wholwh** [comment]
已解决,日历事件项的用创建的日历事件项删除才行,不是创建时传入的id.
